title: AI course
tagline: 期末專題

author:
  name: kevin su
  url: https://www.facebook.com/profile.php?id=100014598376662

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme

paginate: 3

tags_path: /tags/
categories_path: /categories/

remote_theme: zivong/jekyll-theme-hydure
#theme: jekyll-theme-hydure
